//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewVersion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckOut
    {
        public int CheckOutID { get; set; }
        public int CartID { get; set; }
        public string DeliveryFree { get; set; }
        public string ProductName { get; set; }
        public string Price { get; set; }
        public string TotalPrice { get; set; }
        public int Quantity { get; set; }
        public bool CheckOutStatus { get; set; }
        public string ProductDetails { get; set; }
        public decimal SubTotal { get; set; }
    
        public virtual ShoppingCart ShoppingCart { get; set; }
    }
}
