//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewVersion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public int inventoryID { get; set; }
        public string inventoryName { get; set; }
        public string inventorySupplier { get; set; }
        public int inventoryQuantity { get; set; }
    }
}
