//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewVersion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int ReviewID { get; set; }
        public System.DateTime ReviewDate { get; set; }
        public int ReviewRating { get; set; }
        public string ReviewImage { get; set; }
        public string ReviewDescription { get; set; }
        public int ProductID { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
