//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewVersion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipper
    {
        public int shipperID { get; set; }
        public string shipperName { get; set; }
        public string shipperEmail { get; set; }
        public string shipperPhone { get; set; }
        public string shipperAddress { get; set; }
    }
}
