//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewVersion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public int supplierID { get; set; }
        public string supplierBranch { get; set; }
        public string supplierEmail { get; set; }
        public string supplierPhone { get; set; }
        public string supplierAddress { get; set; }
    }
}
